#!/usr/bin/env bash
set -e

if pkill -f mediaremote-adapter.pl; then
    echo "Existing instance killed"
fi

media-control stream --no-diff  | jq -r --unbuffered '
    [
       if (.payload | length) == 0 then "gone"
       elif .payload.playbackRate == 1 then "playing"
       else "paused" end,
       (if .payload.title == "" then "N/A" else .payload.title end),
       (if .payload.album == "" then "N/A" else .payload.album end),
       (if .payload.artist == "" then "N/A" else .payload.artist end),
       (if .payload.bundleIdentifier == "" then "N/A" else .payload.bundleIdentifier end)
       ] | @tsv' | while IFS=$'\t' read -r STATE TITLE ALBUM ARTIST APP_NAME; do
    sketchybar --trigger media_change_custom \
        STATE="$STATE" TITLE="$TITLE" ALBUM="$ALBUM" ARTIST="$ARTIST" APP_NAME="$APP_NAME"
    done
